language: generic

sudo: required

services:
    - docker

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE

env:
    - DOCKER_IMAGE=centos:8
    - DOCKER_IMAGE=fedora:30
    - DOCKER_IMAGE=fedora:31
    - DOCKER_IMAGE=fedora:32
    - DOCKER_IMAGE=fedora:rawhide

matrix:
    allow_failures:
        - env: DOCKER_IMAGE=fedora:rawhide

before_deploy:
    - openssl aes-256-cbc -K $encrypted_d7be5057a7c8_key -iv $encrypted_d7be5057a7c8_iv -in .copr.enc -out .copr -d

deploy:
    skip_cleanup: true
    provider: script
    script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ fedora:latest /bin/sh -c "dnf install -y copr-cli && copr-cli --config .copr build --chroot epel-8-x86_64 --chroot fedora-31-x86_64 --chroot fedora-32-x86_64 --nowait simc/stable python-pysteps.spec"
    on:
        branch: master
        condition: $DOCKER_IMAGE = centos:8
